### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by bambuladimon** [bambuladimon/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by dima2-binary** [comment]
**EXPERIENCE**

10/2017 - 03/2018
European Guared Consulting - junior frontend dev

03/2018 - 05/2018
Perspective Studio -  junior frontend dev

05/2018 - 11/2018
Freelance -  frontend dev

11/2018 - 03/2021
TSG - Junior Quality Assurance Engineer. 

03/21 - to this time
TSG - trainee as a frontend dev
